apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: order-platform
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: orderplatform
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: SPRING_DATASOURCE_PASSWORD
            - name: POSTGRES_MULTIPLE_DATABASES
              value: orders_db,inventory_db
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "orderplatform"]
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-db
          configMap:
            name: postgres-init
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: order-platform
data:
  init-db.sql: |
    CREATE DATABASE orders_db;
    CREATE DATABASE inventory_db;
